window.InmoSanityConfig = {
	projectId: "pv96nhm8",
	dataset: "production",
	apiVersion: "2026-04-02",
	useCdn: true,
	timeoutMs: 8000,
	liveRefreshIntervalMs: 300000,
	listenDebounceMs: 5000,
	listenVisibility: "transaction",
	defaultDurationMs: 30000,
	panelRevealDelayMs: 1000,
	tvPerformanceMode: true,
	panelDynamicBlur: true,
	imageFormat: "auto",
	imageQuality: 68,
	imageMaxWidth: 1920,
	imageMaxHeight: 3200,
	publicBaseUrl: "",
	settingsType: "siteSettings",
	propertyType: "inmueble",
	propertyTypes: ["inmueble"],
};