window.InmoSanityConfig = {
projectId: "pv96nhm8",
dataset: "production",
apiVersion: "2026-04-02",
useCdn: true,
timeoutMs: 8000,
defaultDurationMs: 20000,
panelRevealDelayMs: 1000,
tvPerformanceMode: true,
panelDynamicBlur: true,
imageFormat: "webp",
imageQuality: 72,
imageMaxWidth: 2160,
imageMaxHeight: 3840,
publicBaseUrl: "",
settingsType: "siteSettings",
propertyType: "inmueble",
propertyTypes: ["inmueble", "property"],
};